//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: mcvspec Created :
// Initializer: mcvspec.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "mcvspecFunctionMap.h"
#include  <XSFunctions/Utilities/XSModelFunction.h>

extern "C" int Mcvspec_Init(Tcl_Interp* tclInterp);
extern "C" int Mcvspec_SafeInit(Tcl_Interp* tclInterp);

int Mcvspec_Init(Tcl_Interp* tclInterp)
{
        return Mcvspec_SafeInit(tclInterp);
}

int Mcvspec_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "mcvspec";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        createmcvspecFunctionMap();
        XSModelFunction::updateComponentList
              ("/Users/students/ciro/mcvspec/model.dat");
        return TCL_OK;

}

