//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: mcvspec
// Function header: mcvspecFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <XSFunctions/Utilities/funcType.h>

class    XSModelFunction;

extern    ModelFunctionMap  XSFunctionMap;

void  createmcvspecFunctionMap();

extern "C"  {


	xsf77Call    mcvspec_;
}


#endif
